### ISSUE TITLE
Error with JSON.stringify

### ISSUE THREAD

**Issue by thundo** [sbarski/run-local-lambda#1]
Hello @sbarski,

I'm using your runner with the Node v4.3 optional callback. However this code:

```
exports.handler = function (event, context, callback) {
    callback(new Error('bad things happen'));
};
```

returns:
```
errorMessage: {}
```

I think this is due to the fact that `Error` relies on non-enumerable properties and therefore is not per-se ["stringifable"](https://github.com/sbarski/run-local-lambda/blob/b94e89ac9a23e133f86439614545bff45ffed3ca/bin/run-local-lambda.js#L116).

Thanks

**Comment by sbarski** [comment]
Hi @thundo, that's a good point! 

I'll update the runner now so that it works properly with the `Error` object.

**Comment by sbarski** [comment]
@thundo I've just a pushed a new version of the module that handles `Error`. 

Please let me know if you see any other issues or if you have any requests!

**Comment by thundo** [comment]
Nice, works for me!

Thank you for your quick response.
